### PR TITLE
Fix: Mentorship bean validation

### LINKED ISSUE #438: bug: Spring validation is not been applied
### Describe the bug
APIs and models have not null, not empty and other validation constraints, but they are not been called by the framework.

Probably has a mix of different libraries and setup to validade from Spring and/or jakarta.validation
`import org.springframework.validation.annotation.Validated;` @Validated versus `import jakarta.validation.Valid;` @Valid 

### To Reproduce

Detailed steps to reproduce the behaviour:

1. Create a mentor from public api 
2. Send request without mandatory attributes 
3. Spring does not return invalid object 
4. It return 500 Status instead of NOT_ACCEPTABLE (406) 
5. this exception is because of the database restriction, but the 

### Expected behaviour

 NOT_ACCEPTABLE (406)  status code is returned and saying the atributes that are mandatory

### Screenshots

Image

### Reproducibility

- [x] The bug is reproducible consistently.

### Impact

- [x] The bug affects critical functionality.

### Additional context

Review all put APIs for pages, mentor, mentee and member

### PR DESCRIPTION
**Pull request by Sowmiya07**
## Description

* Added @Valid to create and update of member, mentor and mentee
* Fixed field annotations to standard placement
* Removed unused imports
* Remove redundant annotation from constructors

## Related Issue
Fix #438

Please link to the issue here

## Change Type

- [X] Bug Fix
- [ ] New Feature
- [ ] Code Refactor
- [ ] Documentation
- [ ] Test
- [ ] Other

## Screenshots

image
<br/>
image
<br/>
image

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [X] I checked and followed the [contributor guide](../CONTRIBUTING.md)
- [X] I have tested my changes locally.

### CODE REVIEW

File: src/main/java/com/wcc/platform/controller/MemberController.java [hunk 1]
```diff
@@ -85,7 +86,7 @@ public ResponseEntity<List<MentorDto>> getAllMentors() {
   @PostMapping("/members")
   @Operation(summary = "API to submit member registration")
   @ResponseStatus(HttpStatus.CREATED)
-  public ResponseEntity<Member> createMember(@RequestBody final Member member) {
+  public ResponseEntity<Member> createMember(@Valid @RequestBody final Member member) {
```
Comment (dricazenck) [inline src/main/java/com/wcc/platform/controller/MemberController.java]: @Sowmiya07 could you make sure the error message is also returned? So the frontend would know why it is a bad request? I think usually the validation say that attribute x cannot be null/empty. Just to confirm this is been returned. From the screenshot I cannot see that. 

Could you please create another issue to fix all other controllers/beens to have the correct annotations in place?

**Review by dricazenck — APPROVED** [review]
