### PR TITLE
fix: Token auth principal type

### LINKED ISSUE #561: bug: Invalid authentication principal for /mentors/{mentorId}/applications
### Describe the bug

´´´
curl -X 'GET' \
  'https://wcc-backend-dev.fly.dev/api/platform/v1/mentors/2/applications' \
  -H 'accept: */*' \
  -H 'X-API-KEY: XXXXXX'
´´´

Response:
403 status code

Body:
´´´
{
  "status": 403,
  "message": "Invalid authentication principal",
  "details": "uri=/api/platform/v1/mentors/2/applications"
}
´´´

### PR DESCRIPTION
**Pull request by goelsonali**
## Description

Fixing the issue 

Closes #561 

## Change Type

- [x] Bug Fix
- [ ] New Feature
- [ ] Code Refactor
- [ ] Documentation
- [ ] Test
- [ ] Other

## Screenshots

image

image

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] I checked and followed the [contributor guide](../CONTRIBUTING.md)
- [x] I have tested my changes locally.

### CODE REVIEW

File: src/main/java/com/wcc/platform/configuration/TokenAuthFilter.java [hunk 1]
```diff
@@ -76,10 +75,15 @@ protected void doFilterInternal(
         SecurityContextHolder.getContext().setAuthentication(authentication);
```
Comment (womencodingcommunity) [inline src/main/java/com/wcc/platform/configuration/TokenAuthFilter.java]: **[WARNING]** `account.getRoles()` can be `null` — `UserAccount.getPermissions()` already guards against this with `if (roles == null || CollectionUtils.isEmpty(roles))`, confirming null is a realistic value. Calling `.stream()` on a null list throws `NullPointerException` inside the auth filter, causing a 500 response for any user whose account has null roles. This is a regression introduced by this PR (the old code never called `getRoles()`).

```java
final var authorities =
    account.getRoles() == null
        ? List.of()
        : account.getRoles().stream()
            .map(role -> new SimpleGrantedAuthority(role.name()))
            .toList();
```
